# Generated by Django 4.0.2 on 2022-04-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_usercredentials_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
