# Generated by Django 4.0.2 on 2022-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_usercredentials_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
