# Generated by Django 4.0.2 on 2022-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_usercredentials_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
