# Generated by Django 4.0.2 on 2022-04-29 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_usercredentials_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_quote',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='gallons_requested',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='suggested_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='total_due',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='suggested_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
