# Generated by Django 4.0.2 on 2022-04-29 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_fuel_quote_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_quote',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
