# Generated by Django 4.0.2 on 2022-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_fuel_quote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_quote',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
