# Generated by Django 4.0.2 on 2022-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_alter_fuel_quote_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_quote',
            name='user',
        ),
        migrations.AddField(
            model_name='fuel_quote',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
