# Generated by Django 4.0.2 on 2022-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_remove_fuel_quote_user_fuel_quote_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_quote',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
