# Generated by Django 4.0.2 on 2022-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_fuel_quote_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing_Module',
        ),
    ]
