# Generated by Django 4.0.2 on 2022-05-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_alter_fuel_quote_gallons_requested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Initial_Quote',
        ),
    ]
