# Generated by Django 4.0.2 on 2022-05-06 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_delete_initial_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('suggested_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_due', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
