# Generated by Django 4.0.2 on 2022-05-07 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0020_initial_quote_suggested_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Initial_Quote',
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='delivery_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='gallons_requested',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='suggested_price',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='total_due',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
