# Generated by Django 4.0.2 on 2022-03-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_profile_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.IntegerField()),
                ('delivery_address', models.DateField()),
            ],
        ),
    ]
