# Generated by Django 4.0.2 on 2022-03-06 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_fuel_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_quote',
            name='delivery_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fuel_quote',
            name='suggested_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fuel_quote',
            name='total_due',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='delivery_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuel_quote',
            name='gallons_requested',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
