# Generated by Django 4.0.2 on 2022-03-06 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_fuel_quote_delivery_date_fuel_quote_suggested_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
