# Generated by Django 4.0.2 on 2022-03-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_pricing_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='no_password', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='new_user', max_length=50),
        ),
    ]
