# Generated by Django 4.0.3 on 2022-03-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
