# Generated by Django 4.0.3 on 2022-03-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_usercredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
